services:
    python-311:
        image: local/${SAIL_PROJECT}:${SAIL_VERSION}
        build:
            args:
                SAIL_BASE_IMAGE: ${SAIL_BASE_IMAGE}
                SAIL_PROJECT: ${SAIL_PROJECT}
                SAIL_VERSION: ${SAIL_VERSION}
                SAIL_VERSION_CODENAME: ${SAIL_VERSION_CODENAME}
                SAIL_GROUP: ${SAIL_GROUP}
                SAIL_USER: ${SAIL_USER}
                SAIL_USERNAME: ${SAIL_USERNAME}
                SAIL_PASSWORD: ${SAIL_PASSWORD}
            context: .
        container_name: ${SAIL_BASENAME}-${SAIL_PROJECT}-${SAIL_VERSION_WS}
        extra_hosts:
            - host.docker.internal:host-gateway
            - gateway.docker.internal:host-gateway
        entrypoint: /usr/local/bin/entrypoint-loop.sh
        environment:
          - SAIL_GROUP=${SAIL_GROUP}
          - SAIL_USER=${SAIL_USER}
          - SAIL_USERNAME=${SAIL_USERNAME}
        volumes:
            - ${SAIL_HOST_WORKSPACE}:${SAIL_WORKSPACE}
            - ../data/.cache:/home/${SAIL_USERNAME}/.cache
            - ../data/.config:/home/${SAIL_USERNAME}/.config
            - ../data/.local:/home/${SAIL_USERNAME}/.local
            - ../data/.npm:/home/${SAIL_USERNAME}/.npm
            - ../data/.vscode-server:/home/${SAIL_USERNAME}/.vscode-server
        networks:
            - workspace-project-net
            - workspace-net

networks:
    workspace-project-net:
        name: ${COMPOSE_PROJECT_NAME}-net
        driver: bridge

    workspace-net:
        external: true
